# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bash .circleci/deps.sh

      - run:
          name: build steps
          command: |
            bash .circleci/builds.sh
            
      - run: 
          name: background server for tests
          command: |
            source env/bin/activate
            python std-api-server/server.py
          background: true
        
      - run: bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' 127.0.0.1:5555/system/test" != "200" ]]; do sleep 1; done'
      
      - run: 
          name: server tests
          command: bash std-api-server/test.sh
